---
# Install Ansible Docker Compose Collection dependencies
- name: Install pip (Python package installer)
  apt:
    name: python3-pip
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Install Docker SDK for Python
  pip:
    name: docker
    executable: pip3
  become: yes

- name: Install docker-compose Python module
  pip:
    name: docker-compose
    executable: pip3
  become: yes

# Upload container configurations

- name: Start containers with Docker Compose
  community.docker.docker_compose:
    project_src: "/home/{{ username }}/containers/{{ item }}"
  loop: "{{ containers }}"
